import antfu from "@antfu/eslint-config";

// Frontend (React 19 + Vite) lint baseline. Uses @antfu/eslint-config (the
// pma-web required gate) but preserves this project's established formatting
// (semicolons + double quotes) instead of mass-reformatting working code.
export default antfu(
  {
    type: "app",
    react: true,
    typescript: true,
    stylistic: {
      semi: true,
      quotes: "double",
    },
    ignores: [
      "dist/**",
      "src/app/routeTree.gen.ts", // generated by the TanStack Router plugin
    ],
  },
  {
    // TanStack Router file-based routes export `Route` (a non-component) next to
    // the page component — that's the framework convention, not an HMR mistake.
    files: ["src/app/routes/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // Keep antfu's logic/quality rules, but don't let the JSX formatters split
    // `label {value}` across lines — that fixer can drop significant whitespace.
    rules: {
      "style/multiline-ternary": "off",
      "style/jsx-one-expression-per-line": "off",
    },
  },
);
